osx_image: xcode7.3
language: objective-c
xcode_project: URLHelper.xcodeproj
script: xcodebuild -project URLHelper.xcodeproj -scheme "URLHelper" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
